### ISSUE TITLE
Page Numbers

### ISSUE THREAD

**Issue by sebelk** [sinedied/backslide#54]
Hi, this tool is great.
How can I disable the slide numbers at bottom bar? 
Thanks in advance!
SB

**Comment by sinedied** [comment]
You can use some css:
```css
.remark-slide-number {
  display: none !important;
}
```
