### ISSUE TITLE
CSS images with relative paths are not inlined (PDF or HTML)

### ISSUE THREAD

**Issue by mjpieters** [sinedied/backslide#73]
When the stylesheet contains something like:

```scss
.acmecorp {
    display: flex;
    flex-direction: row;
    justify-content: center;
    p {
        text-align: left;
        padding-left: 3em;
        background-image: url(assets/acmelogo.png);
        background-size: 2em 2em;
        background-repeat: no-repeat;
        background-position: top 0.3em left 0.3em; 
    }
}
```

things look great when serving, but not-so-great when exporting to HTML or PDF. That's because the regular expression for CSS image URLs only matches `url(file://...)` references, not relative references:

```js
const CssImagesRegExp = /(url\()((file:\/\/)[^)]+)(\))/gm;
```

Can this be updated to also pick up paths that do not start with a scheme or slash? Anything that doesn't start with `[a-z]+:` should be seen as a relative path, but perhaps limiting this to `http:`, `https:` and `data:` makes for an easier negative-lookbehind pattern to write.
